package estrella;

import static estrella.Conexion.getConection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class GUI_RegisCompra extends javax.swing.JFrame {

    public GUI_RegisCompra() {
        initComponents();
    }

    PreparedStatement ps, ps2;
    ResultSet rs;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRegisVent = new javax.swing.JPanel();
        BtnRegisComp = new javax.swing.JButton();
        FieldPrecioCompra = new javax.swing.JTextField();
        LabelPrecioCompra = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        LineaDivisora = new javax.swing.JLabel();
        FondoText3 = new javax.swing.JLabel();
        FieldCantidad = new javax.swing.JTextField();
        LabelCantidad = new javax.swing.JLabel();
        FondoText7 = new javax.swing.JLabel();
        IdProducto = new javax.swing.JTextField();
        FondoText9 = new javax.swing.JLabel();
        LabelCostoTotal1 = new javax.swing.JLabel();
        IdCompra = new javax.swing.JTextField();
        FondoText10 = new javax.swing.JLabel();
        LabelidCompra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelRegisVent.setBackground(new java.awt.Color(248, 248, 248));
        PanelRegisVent.setPreferredSize(new java.awt.Dimension(1050, 600));
        PanelRegisVent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnRegisComp.setBackground(new java.awt.Color(248, 248, 248));
        BtnRegisComp.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        BtnRegisComp.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegisComp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Boton_morado2.png"))); // NOI18N
        BtnRegisComp.setText("Registrar");
        BtnRegisComp.setBorderPainted(false);
        BtnRegisComp.setContentAreaFilled(false);
        BtnRegisComp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegisComp.setFocusPainted(false);
        BtnRegisComp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnRegisComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegisCompActionPerformed(evt);
            }
        });
        PanelRegisVent.add(BtnRegisComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 250, 90));

        FieldPrecioCompra.setBackground(new java.awt.Color(232, 232, 232));
        FieldPrecioCompra.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        FieldPrecioCompra.setForeground(new java.awt.Color(51, 51, 51));
        FieldPrecioCompra.setBorder(null);
        PanelRegisVent.add(FieldPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 180, -1));

        LabelPrecioCompra.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        LabelPrecioCompra.setForeground(new java.awt.Color(0, 0, 0));
        LabelPrecioCompra.setText("Precio Compra");
        PanelRegisVent.add(LabelPrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, -1));

        Titulo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 30)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("Registar Compra");
        PanelRegisVent.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        LineaDivisora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Linea001.png"))); // NOI18N
        PanelRegisVent.add(LineaDivisora, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 870, 20));

        FondoText3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CampoDeText.png"))); // NOI18N
        PanelRegisVent.add(FondoText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        FieldCantidad.setBackground(new java.awt.Color(232, 232, 232));
        FieldCantidad.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        FieldCantidad.setForeground(new java.awt.Color(51, 51, 51));
        FieldCantidad.setBorder(null);
        PanelRegisVent.add(FieldCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 180, -1));

        LabelCantidad.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        LabelCantidad.setForeground(new java.awt.Color(0, 0, 0));
        LabelCantidad.setText("Cantidad");
        PanelRegisVent.add(LabelCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, -1, -1));

        FondoText7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CampoDeText.png"))); // NOI18N
        PanelRegisVent.add(FondoText7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        IdProducto.setBackground(new java.awt.Color(232, 232, 232));
        IdProducto.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        IdProducto.setForeground(new java.awt.Color(51, 51, 51));
        IdProducto.setBorder(null);
        PanelRegisVent.add(IdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 180, -1));

        FondoText9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CampoDeText.png"))); // NOI18N
        PanelRegisVent.add(FondoText9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        LabelCostoTotal1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        LabelCostoTotal1.setForeground(new java.awt.Color(0, 0, 0));
        LabelCostoTotal1.setText("Id Producto");
        PanelRegisVent.add(LabelCostoTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        IdCompra.setBackground(new java.awt.Color(232, 232, 232));
        IdCompra.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        IdCompra.setForeground(new java.awt.Color(51, 51, 51));
        IdCompra.setBorder(null);
        PanelRegisVent.add(IdCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 180, -1));

        FondoText10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/CampoDeText.png"))); // NOI18N
        PanelRegisVent.add(FondoText10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, -1, -1));

        LabelidCompra.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        LabelidCompra.setForeground(new java.awt.Color(0, 0, 0));
        LabelidCompra.setText("Id Compra");
        PanelRegisVent.add(LabelidCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRegisVent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelRegisVent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegisCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegisCompActionPerformed

        Connection con = null;

        try {

            con = getConection();
            ps = con.prepareStatement("INSERT INTO compra(id, id_producto, cantidad, precio_compra) VALUES (?,?,?,?)");
            ps.setInt(1, Integer.parseInt(IdCompra.getText()));
            ps.setInt(2, Integer.parseInt(IdProducto.getText()));
            ps.setInt(3, Integer.parseInt(FieldCantidad.getText()));
            ps.setInt(4, Integer.parseInt(FieldPrecioCompra.getText()));

            int res = ps.executeUpdate();

           
            if (res > 0 ) {
                JOptionPane.showMessageDialog(null, "Compra Exitosa");
            } else {
                JOptionPane.showMessageDialog(null, "Error al Guardar la Compra");
                //  System.out.println("Error al Guardar Producto");
            }

            con.close();

        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_BtnRegisCompActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        GUI_RegisCompra ventanaRegisCompra = new GUI_RegisCompra();
        ventanaRegisCompra.setBounds(0, 0, 1050, 600);
        ventanaRegisCompra.setVisible(true);
        ventanaRegisCompra.setResizable(false);
        ventanaRegisCompra.setLocationRelativeTo(null);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //  new GUI_Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegisComp;
    private javax.swing.JTextField FieldCantidad;
    private javax.swing.JTextField FieldPrecioCompra;
    private javax.swing.JLabel FondoText10;
    private javax.swing.JLabel FondoText3;
    private javax.swing.JLabel FondoText7;
    private javax.swing.JLabel FondoText9;
    private javax.swing.JTextField IdCompra;
    private javax.swing.JTextField IdProducto;
    private javax.swing.JLabel LabelCantidad;
    private javax.swing.JLabel LabelCostoTotal1;
    private javax.swing.JLabel LabelPrecioCompra;
    private javax.swing.JLabel LabelidCompra;
    private javax.swing.JLabel LineaDivisora;
    public static javax.swing.JPanel PanelRegisVent;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
