/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estrella;

import static estrella.GUI_ConsulCliente.PanelConsulCliente;
import static estrella.GUI_ConsulProd.PanelConsulPro;
import static estrella.GUI_ModiCliente.PanelModifClient;
import static estrella.GuiRegisCliente.PanelRegisClient;
import static estrella.GUI_RegisProducto.PanelRegisPro;
import java.awt.BorderLayout;

/**
 *
 * @author Andres
 */
public class GUI_Clientes extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Producto
     */
    public GUI_Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelClient = new javax.swing.JPanel();
        BotonFindClient = new javax.swing.JButton();
        BotonAddClient = new javax.swing.JButton();
        BotonModClient = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        LineaDivisora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelClient.setBackground(new java.awt.Color(248, 248, 248));
        PanelClient.setPreferredSize(new java.awt.Dimension(1050, 600));

        BotonFindClient.setBackground(new java.awt.Color(248, 248, 248));
        BotonFindClient.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        BotonFindClient.setForeground(new java.awt.Color(255, 255, 255));
        BotonFindClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BotonM001.png"))); // NOI18N
        BotonFindClient.setText("Buscar Cliente");
        BotonFindClient.setBorderPainted(false);
        BotonFindClient.setContentAreaFilled(false);
        BotonFindClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonFindClient.setFocusPainted(false);
        BotonFindClient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonFindClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFindClientActionPerformed(evt);
            }
        });

        BotonAddClient.setBackground(new java.awt.Color(248, 248, 248));
        BotonAddClient.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        BotonAddClient.setForeground(new java.awt.Color(255, 255, 255));
        BotonAddClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BotonM002.png"))); // NOI18N
        BotonAddClient.setText("Agregar Cliente");
        BotonAddClient.setBorderPainted(false);
        BotonAddClient.setContentAreaFilled(false);
        BotonAddClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAddClient.setFocusPainted(false);
        BotonAddClient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonAddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAddClientActionPerformed(evt);
            }
        });

        BotonModClient.setBackground(new java.awt.Color(248, 248, 248));
        BotonModClient.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        BotonModClient.setForeground(new java.awt.Color(255, 255, 255));
        BotonModClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BotonM003.png"))); // NOI18N
        BotonModClient.setText("Modificar Cliente");
        BotonModClient.setBorderPainted(false);
        BotonModClient.setContentAreaFilled(false);
        BotonModClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonModClient.setFocusPainted(false);
        BotonModClient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonModClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModClientActionPerformed(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 30)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 0, 0));
        Titulo.setText("Clientes");

        LineaDivisora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Linea001.png"))); // NOI18N

        javax.swing.GroupLayout PanelClientLayout = new javax.swing.GroupLayout(PanelClient);
        PanelClient.setLayout(PanelClientLayout);
        PanelClientLayout.setHorizontalGroup(
            PanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientLayout.createSequentialGroup()
                .addGroup(PanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelClientLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(PanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LineaDivisora, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Titulo)))
                    .addGroup(PanelClientLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addGroup(PanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonFindClient, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonAddClient, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonModClient, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(90, 90, 90))
        );
        PanelClientLayout.setVerticalGroup(
            PanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClientLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelClientLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(LineaDivisora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Titulo))
                .addGap(52, 52, 52)
                .addComponent(BotonFindClient, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonAddClient, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonModClient, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonFindClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFindClientActionPerformed

        GUI_ConsulCliente ventanaConsulCliente = new GUI_ConsulCliente();
        ventanaConsulCliente.setSize(1050, 600);
        ventanaConsulCliente.setLocation(0,0);

        PanelClient.removeAll();
        PanelClient.add(PanelConsulCliente, BorderLayout.CENTER);
        PanelClient.revalidate();
        PanelClient.repaint();
    }//GEN-LAST:event_BotonFindClientActionPerformed

    private void BotonAddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAddClientActionPerformed

        GuiRegisCliente ventanaRegisCliente = new GuiRegisCliente();
        ventanaRegisCliente.setSize(1050, 600);
        ventanaRegisCliente.setLocation(0,0);

        PanelClient.removeAll();
        PanelClient.add(PanelRegisClient, BorderLayout.CENTER);
        PanelClient.revalidate();
        PanelClient.repaint();
    }//GEN-LAST:event_BotonAddClientActionPerformed

    private void BotonModClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModClientActionPerformed

        GUI_ModiCliente ventanaModiCliente = new GUI_ModiCliente();
        ventanaModiCliente.setSize(1050, 600);
        ventanaModiCliente.setLocation(0,0);

        PanelClient.removeAll();
        PanelClient.add(PanelModifClient, BorderLayout.CENTER);
        PanelClient.revalidate();
        PanelClient.repaint();
    }//GEN-LAST:event_BotonModClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        GUI_Clientes ventanaClientes = new GUI_Clientes();
        ventanaClientes.setBounds(0, 0, 1050, 600);
        ventanaClientes.setVisible(true);
        ventanaClientes.setResizable(false);
        ventanaClientes.setLocationRelativeTo(null);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new GUI_Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAddClient;
    private javax.swing.JButton BotonFindClient;
    private javax.swing.JButton BotonModClient;
    private javax.swing.JLabel LineaDivisora;
    public static javax.swing.JPanel PanelClient;
    private javax.swing.JLabel Titulo;
    // End of variables declaration//GEN-END:variables
}
