/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estrella;

import static estrella.Conexion.getConection;
import static estrella.GuiConsulProd.PanelConsulPro;
import static estrella.GUI_ModiProducto.PanelModiProduct;
import static estrella.GUI_RegisProducto.PanelRegisPro;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres
 */
public class GUI_ModifiLoginN extends javax.swing.JFrame {

    PreparedStatement ps;
    Statement st;
    ResultSet rs;
    String nombre, contraseña;
    
    public GUI_ModifiLoginN() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelModifiLogNuevoo = new javax.swing.JPanel();
        jTextNombreActual = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldContraseña = new javax.swing.JTextField();
        jButtonActualizar = new javax.swing.JButton();
        ImagenHome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelModifiLogNuevoo.setBackground(new java.awt.Color(248, 248, 248));
        PanelModifiLogNuevoo.setPreferredSize(new java.awt.Dimension(1050, 600));
        PanelModifiLogNuevoo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextNombreActual.setBackground(new java.awt.Color(109, 103, 110));
        jTextNombreActual.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextNombreActual.setForeground(new java.awt.Color(255, 255, 255));
        jTextNombreActual.setBorder(null);
        PanelModifiLogNuevoo.add(jTextNombreActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 210, 29));

        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BontonBuscar_Morado.png"))); // NOI18N
        jButtonBuscar.setBorderPainted(false);
        jButtonBuscar.setContentAreaFilled(false);
        jButtonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBuscar.setFocusPainted(false);
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        PanelModifiLogNuevoo.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, 70));

        jTextFieldNombre.setBackground(new java.awt.Color(109, 103, 110));
        jTextFieldNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldNombre.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldNombre.setBorder(null);
        PanelModifiLogNuevoo.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 300, 32));

        jTextFieldContraseña.setBackground(new java.awt.Color(109, 103, 110));
        jTextFieldContraseña.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldContraseña.setBorder(null);
        PanelModifiLogNuevoo.add(jTextFieldContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 300, 30));

        jButtonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BotonModificar_morado.png"))); // NOI18N
        jButtonActualizar.setBorderPainted(false);
        jButtonActualizar.setContentAreaFilled(false);
        jButtonActualizar.setFocusPainted(false);
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        PanelModifiLogNuevoo.add(jButtonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 190, -1));

        ImagenHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ModificarLoginFondo.png"))); // NOI18N
        PanelModifiLogNuevoo.add(ImagenHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1062, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelModifiLogNuevoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 612, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PanelModifiLogNuevoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        // TODO add your handling code here:

        Connection con = null;

        try {

            con = getConection();
            ps = con.prepareStatement("UPDATE login SET nombre = ?, password= ?  where nombre= ?");

            ps.setString(1, jTextFieldNombre.getText());
            ps.setString(2, jTextFieldContraseña.getText());
            ps.setString(3, jTextNombreActual.getText());

            int res = ps.executeUpdate();

            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Usuario Modificado");
            } else {
                JOptionPane.showMessageDialog(null, "Error al Modificar el usuario");
                //System.out.println("Error al Guardar Producto");
            }

        } catch (Exception e) {
            System.err.println(e);
        }

        /*
        ps = con.prepareStatement("UPDATE login  SET nombre password = ? Where nombre = ?  VALUES (?,?)");
        //ps3.setInt(1, Integer.parseInt(IdProducto.getText()));
        ps.setString(1, jTextFieldNombre.getText());
        ps.setString(2, jTextFieldContraseña.getText());
        */
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        Connection con = null;

        try {

            con = getConection();
            String sql = "SELECT * FROM public.login " + "WHERE nombre = '" + jTextNombreActual.getText() + "'";
            ps = con.prepareStatement(sql);

            rs = ps.executeQuery();

            if (rs.next()) {
                jTextFieldNombre.setText(rs.getString("nombre"));
                jTextFieldContraseña.setText(rs.getString("password"));

            } else {
                JOptionPane.showMessageDialog(null, "No existe el usuario");
            }

        } catch (Exception e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        GUI_ModifiLoginN ventanaModifiLoginNuevo = new GUI_ModifiLoginN();
        ventanaModifiLoginNuevo.setBounds(0, 0, 1050, 600);
        ventanaModifiLoginNuevo.setVisible(true);
        ventanaModifiLoginNuevo.setResizable(false);
        ventanaModifiLoginNuevo.setLocationRelativeTo(null);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new GUI_Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel ImagenHome;
    public static javax.swing.JPanel PanelModifiLogNuevoo;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JTextField jTextFieldContraseña;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextNombreActual;
    // End of variables declaration//GEN-END:variables
}
