package estrella;

import static estrella.Conexion.getConection;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.table.DefaultTableModel;

public class GuiConsulVent extends javax.swing.JFrame {

  public static String campo = "";

  public GuiConsulVent() {
    initComponents();
  }

  PreparedStatement ps;
  ResultSet rs;

  /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  **/
  @SuppressWarnings("unchecked")
    /**
    *  No es posible modificar las lineas de codigo dentro del metodo initComponents.
    **/
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelConsulVent = new javax.swing.JPanel();
        BtnRegisVent = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        LineaDivisora = new javax.swing.JLabel();
        BtnBuscarProd = new javax.swing.JButton();
        BuscarProdu = new javax.swing.JTextField();
        FondoText10 = new javax.swing.JLabel();
        LabelBusqueda = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboBusqueda = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableVent = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelConsulVent.setBackground(new java.awt.Color(248, 248, 248));
        PanelConsulVent.setPreferredSize(new java.awt.Dimension(1050, 600));
        PanelConsulVent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnRegisVent.setBackground(new java.awt.Color(248, 248, 248));
        BtnRegisVent.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        BtnRegisVent.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegisVent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Boton_morado2.png"))); // NOI18N
        BtnRegisVent.setText("Registrar");
        BtnRegisVent.setBorderPainted(false);
        BtnRegisVent.setContentAreaFilled(false);
        BtnRegisVent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnRegisVent.setFocusPainted(false);
        BtnRegisVent.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnRegisVent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegisVentActionPerformed(evt);
            }
        });
        PanelConsulVent.add(BtnRegisVent, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, 250, 90));

        Titulo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 30)); // NOI18N
        Titulo.setText("Consultar Venta");
        PanelConsulVent.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        LineaDivisora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Linea001.png"))); // NOI18N
        PanelConsulVent.add(LineaDivisora, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 870, 20));

        BtnBuscarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Boton_Buscar.png"))); // NOI18N
        BtnBuscarProd.setBorderPainted(false);
        BtnBuscarProd.setContentAreaFilled(false);
        BtnBuscarProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnBuscarProd.setFocusPainted(false);
        BtnBuscarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarProdActionPerformed(evt);
            }
        });
        PanelConsulVent.add(BtnBuscarProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        BuscarProdu.setBackground(new java.awt.Color(232, 232, 232));
        BuscarProdu.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        BuscarProdu.setForeground(new java.awt.Color(51, 51, 51));
        BuscarProdu.setBorder(null);
        PanelConsulVent.add(BuscarProdu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 150, -1));

        FondoText10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search Bar.png"))); // NOI18N
        PanelConsulVent.add(FondoText10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        LabelBusqueda.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        LabelBusqueda.setText("Buscar:");
        PanelConsulVent.add(LabelBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel3.setText("Buscar por:");
        PanelConsulVent.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        comboBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Codigo" }));
        comboBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBusquedaActionPerformed(evt);
            }
        });
        PanelConsulVent.add(comboBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        tableVent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "cantidad", "costo_total", "estado", "id_cliente", "hora", "fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableVent);

        PanelConsulVent.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 880, 250));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel2.setText("SI DESEA VER TODOS LOS DATOS REGISTRADOS, DEJE LA BARRA DE BUSQUEDA EN BLANCO.");
        PanelConsulVent.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelConsulVent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelConsulVent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    *  No es posible modificar la linea de codigo siguiente.
    **/
    private void BtnRegisVentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegisVentActionPerformed

    /**
    *  No es posible modificar la linea de codigo siguiente.
    **/
    }//GEN-LAST:event_BtnRegisVentActionPerformed

    /**
    *  No es posible modificar la linea de codigo siguiente.
    **/
    private void BtnBuscarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarProdActionPerformed

    Connection con = null;

    if ((comboBusqueda.getSelectedItem().toString()).equals("Codigo")) {

      campo = BuscarProdu.getText();
      String where = "";
      if (!"".equals(campo)) {
        where = "WHERE codigo = '" + campo + "'";
      }

      try {
        DefaultTableModel modelo = new DefaultTableModel();
        tableVent.setModel(modelo);

        ps = null;
        rs = null;
        con = getConection();

        String sql = "SELECT * FROM public.ventas " + where;
        System.out.println(sql);
        ps = con.prepareStatement(sql);
        rs = ps.executeQuery();

        ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
        int cantidadColumnas = rsMd.getColumnCount();

        modelo.addColumn("codigo");
        modelo.addColumn("cantidad");
        modelo.addColumn("costo_total");
        modelo.addColumn("estado");
        modelo.addColumn("id_cliente");
        modelo.addColumn("hora");
        modelo.addColumn("fecha");

        int[] anchos = {50, 50, 50, 50, 50, 50, 50};
        for (int i = 0; i < tableVent.getColumnCount(); i++) {
          tableVent.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }

        while (rs.next()) {
          Object[] filas = new Object[cantidadColumnas];
          for (int i = 0; i < cantidadColumnas; i++) {
            filas[i] = rs.getObject(i + 1);
          }
          modelo.addRow(filas);
        }

      } catch (Exception ex) {
        System.err.println(ex.toString());
      }
      System.out.println(where);
    }
    /**
    *  No es posible modificar la linea de codigo siguiente.
    **/
    }//GEN-LAST:event_BtnBuscarProdActionPerformed

    /**
    *  No es posible modificar la linea de codigo siguiente.
    **/
    private void comboBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBusquedaActionPerformed
    // TODO add your handling code here:
    /**
    *  No es posible modificar la linea de codigo siguiente.
    **/
    }//GEN-LAST:event_comboBusquedaActionPerformed

  /**
  * @param args the command line arguments.
  **/
  public static void main(String args[]) {

    GuiConsulVent ventanaConsulVent = new GuiConsulVent();
    ventanaConsulVent.setBounds(0, 0, 1050, 600);
    ventanaConsulVent.setVisible(true);
    ventanaConsulVent.setResizable(false);
    ventanaConsulVent.setLocationRelativeTo(null);
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
           //  new GUI_Producto().setVisible(true);
      }
        });
  }

    /**
    *  No es posible modificar las lineas de codigo siguientes.
    **/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscarProd;
    private javax.swing.JButton BtnRegisVent;
    private javax.swing.JTextField BuscarProdu;
    private javax.swing.JLabel FondoText10;
    private javax.swing.JLabel LabelBusqueda;
    private javax.swing.JLabel LineaDivisora;
    public static javax.swing.JPanel PanelConsulVent;
    private javax.swing.JLabel Titulo;
    private javax.swing.JComboBox<String> comboBusqueda;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableVent;
    // End of variables declaration//GEN-END:variables
}